// if
const temperature = 41
// if (temperature === 40){
//     console.log("less than 50");
// }else {
//     console.log("temperature is greater than 50");
// }
// console.log("notexecuted");

// const score = 200

// if (score > 100) {
//     const power = "fly"
//     console.log(`User power: ${power}`);
// }


 const balance = 1000

// if (balance > 500) console.log("test");

// if (balance < 500) {
//     console.log("less than 500");
// } else if (balance < 750) {
//     console.log("less than 750");
// } else{
//     console.log("less than 1200");
// }


// const userLoggedIn = true
// const debitcard = true
// const loggedInFromGoogle = false
// const loggedInFromEmail = true

// if (userLoggedIn && debitcard) {
//     console.log("Allow to buy course");
// }
// if (loggedInFromGoogle || loggedInFromEmail){
//     console.log("User logged in");
// }

// switch (key) {
//     case value:
        
//         break;

//     default:
//         break;
// }

// const month = 3

// switch (month) {
//     case 1:
//         console.log("january");
//         break;
//         case 2:
//         console.log("feb");
//         break;
//         case 3:
//         console.log("march");
//         break;
//         case 1:
//         console.log("april");
//         break;

//     default:
//         console.log("default case match");
//         break;
// }
const userEmail = "hitesh@.ai"

if (userEmail) {
    console.log("GOt user email");
} else {
    console.log("Don't have user email");
}

// falsy values

// false,0, -0, BigInt, 0n,"",null,undefined,NaN

//truthy values
// "0", 'false', " ", [],{}, function(){}

const emptyObj = {}

if (Object.keys(emptyObj).length === 0){
    console.log("Object is empty");
}

// Nullish Coalescing Operator (??): null undefined

let val1;
//val1  =5 ?? 10
//val1 = null ?? 10
//val1 = undefined ?? 15

console.log(val1);

const iceTeaPrice = 100
iceTeaPrice <= 80 ? console.log("less than 80") : console.log("more than 80")